# Generated by Django 2.2.7 on 2019-12-02 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='creted_at',
        ),
    ]
