# Generated by Django 2.2.7 on 2019-12-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_contact_creted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='admin@admin.com', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='first_name',
            field=models.CharField(default='anshuman', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(default='singh', max_length=20),
            preserve_default=False,
        ),
    ]
